conky.config = {
	alignment = 'bottom_left',
	background = true,
	default_color = 'ebdbb2',
	color2 = 'b16286',
	color3 = '98971a',
	font = 'Iosevka Nerd Font:size=12',
	gap_x = 150,
	gap_y = 630,
	minimum_width = 400,
	no_buffers = true,
	own_window = true,
	own_window_colour = '282828',
  own_window_transparent = false,
  own_window_type = 'override',
	update_interval = 5.0,
	use_xft = true,
}
conky.text = [[
${color3}>----< MOST NEEDED APPS!!! >----<
${color2}XKILL  ->  ${color}mod+F4
${color2}Rofi DRUN  ->  ${color}mod+d
${color2}Scroll ROFI  ->  ${color}Ctrl+Tab
${color2}Open Terminal      ->  ${color}mod+Enter
${color2}Open Browser       ->  ${color}mod+b
${color2}Open Text Editor   ->  ${color}mod+Shift+t
${color2}Open File manager  ->  ${color}mod+Shift+f
${color2}Kill Focused Window ->  ${color}mod+Shift+q

${color3}>----< SWITCHING BETWEEN LAYOUTS >----<
${color2}Toggle Split       ->  ${color}mod+e
${color2}Toggle Tabbed      ->  ${color}mod+t
${color2}Toggle Stacking    ->  ${color}mod+s
${color2}Toggle Fullscreen  ->  ${color}mod+f
${color2}Center Floating Window  ->  ${color}mod+c
${color2}Toggle Floating    ->  ${color}mod+Shift+Space
${color2}Default MOD key    ->  ${color}<Super> or Windows Key
]]
