conky.config = {
	alignment = 'bottom_left',
	background = true,
	default_color = 'ebdbb2',
	color2 = 'b16286',
	color3 = '98971a',
	font = 'Iosevka Nerd Font:size=12',
	gap_x = 150,
	gap_y = 170,
	minimum_width = 400,
	no_buffers = true,
	own_window = true,
	own_window_colour = '282828',
	own_window_transparent = false,
  own_window_type = 'override',
	update_interval = 5.0,
	use_xft = true,
}
conky.text = [[
${color3}>----< MANIPULATING SCRATHPADS >----<
${color2}Ranger File Manager  ->  ${color}mod+Ctrl+Shift+r
${color2}FakeAss Task Manager ->  ${color}mod+Ctrl+Shift+h
${color2}Pulse Volume Mixer  ->  ${color}mod+Ctrl+Shift+p

${color2}Switch Workspaces [MAIN] ->   ${color}mod+[1-0]
${color2}Send Containers [MAIN]   ->   ${color}mod+Shift+[1-0]
${color2}Switch Workspaces [SEC]  ->   ${color}mod+Ctrl+[1-0]
${color2}Send Containers [SEC]    ->   ${color}mod+Shift+Ctrl+[1-0]

${color2}Change Screen Layouts    ->  ${color}mod+Shift+s
${color2}i3 Power Menu     ->  ${color}mod+Shift+a
]]
