#!/bin/bash
 
#### Autostart ####
#-----------------#
nm-applet &
clipmenud &
xset b off &
numlockx on &
unclutter -idle 21 &
nitrogen --restore &
bash -c ~/.config/bspwm/scripts/polybar.sh &
killall -q dunst | wait; dunst -config ~/.config/dunst/dunstrc &
killall -q sxhkd | wait; sxhkd -c ~/.config/sxhkd/sxhkdrc_bspwm &
killall -q picom | wait; picom --config ~/.config/picom/picom.conf &
sleep 5; notify-send "Welcome to BSPWM :)))" "Have a [REDACTED] day *wink*" &
xinput set-prop "MSFT0001:00 04F3:31BE Touchpad" "libinput Tapping Enabled" 1 &

#### Monitors and workspaces init ####
#------------------------------------#
bash -c ~/.config/bspwm/scripts/monitors.sh &

#### Some needed bspc configs ####
#--------------------------------#

bspc config top_padding     30
bspc config border_width	2
bspc config window_gap		5
 
bspc config split_ratio		        0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config presel_feedback         true
bspc config focus_follows_pointer	false

#### DRACULA ####
#---------------#
bspc config presel_feedback_color "#BD93F9"
bspc config focused_border_color "#8be9fd"
bspc config normal_border_color "#333333"

#### Windows ####
#---------------#
bspc rule -a "mpv" desktop='^4' follow=on
bspc rule -a "Xed" desktop='^5' follow=on
bspc rule -a "Spotify" desktop='^2' follow=on
bspc rule -a "discord" desktop='^3' follow=on
bspc rule -a "ViberPC" desktop='^3' follow=on
bspc rule -a "firefox" desktop='^6' follow=on
bspc rule -a "Protonvpn" desktop='^7' follow=on
bspc rule -a "Deluge-gtk" desktop='^4' follow=on
bspc rule -a "Tor Browser" desktop='^7' follow=on
#bspc rule -a "Mozilla Firefox Private Browsin" desktop='^7' follow=on

#### Scratchpads ####
#-------------------#
bspc rule -a scpad sticky=on state=floating follow=on rectangle=1350x850+285+115
bspc rule -a KeePassXC sticky=on state=floating follow=on rectangle=1350x850+285+115
bspc rule -a Pavucontrol sticky=on state=floating follow=on rectangle=1350x850+285+115


