#!/bin/bash

b_r () { bspc rule -a "$@" ;}
b_c () { bspc config "$@" ;}
_px () { pgrep -x "$@" ;}
_ka () { killall -q "$@" ;}

 
#### Autostart ####
#-----------------#
clipmenud &
numlockx on &
_px sxhkd >/dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc 2>&1 &
_px polybar >/dev/null || bash -c ~/.config/bspwm/scripts/polybar.sh 2>&1 &

#### Monitors and workspaces init ####
#------------------------------------#
bash -c ~/.config/bspwm/scripts/monitors.sh &
source ~/.config/bspwm/themes/nord.sh

#### Some needed bspc configs ####
#--------------------------------#

b_c border_width   2
b_c window_gap	   4
b_c top_padding    30
b_c split_ratio	   0.5

b_c paddingless_monocle       true
b_c borderless_monocle        true
b_c gapless_monocle           true
b_c presel_feedback           true
b_c single_monocle            false
b_c focus_follows_pointer     false
b_c pointer_follows_monitor   true
b_c pointer_follows_focus     false
b_c remove_disabled_monitors  true
b_c remove_unplugged_monitors true

#### Windows ####
#---------------#
b_r "mpv" desktop='^4' follow=on
b_r "Xed" desktop='^5' follow=on
b_r "Code" desktop='^5' follow=on
b_r "Steam" desktop='^8' follow=on
b_r "ZapZap" desktop='^3' follow=on
b_r "Zathura" state=tiled follow=on
b_r "Spotify" desktop='^2' follow=on
b_r "discord" desktop='^3' follow=on
b_r "ViberPC" desktop='^3' follow=on
b_r "Hexchat" desktop='^3' follow=on
b_r "Protonvpn" desktop='^9' follow=on
b_r "Deluge-gtk" desktop='^4' follow=on
b_r "Tor Browser" desktop='^7' follow=on
b_r "VirtualBox Machine" desktop='^9' follow=on
b_r "VirtualBox Manager" desktop='^9' follow=on
b_r "org.mozilla.firefox" desktop='^6' follow=on
b_r "whatsapp-desktop-linux" desktop='^3' follow=on
b_r "Mozilla Firefox Private Browsin" desktop='^7' follow=on

#### Scratchpads ####
#-------------------#
b_r scpad sticky=on state=floating follow=on rectangle=1350x850+285+115
b_r KeePassXC sticky=on state=floating follow=on rectangle=1350x850+285+115
b_r Simplenote sticky=on state=floating follow=on rectangle=1350x850+285+115
b_r Pavucontrol sticky=on state=floating follow=on rectangle=1350x850+285+115

