bindsym $mod+Shift+q kill
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart

# Default Programs
set $term kitty
set $texteditor xed
set $filemanager nautilus

bindsym $mod+Return exec $term
bindsym $mod+Shift+t exec $texteditor
bindsym $mod+Shift+f exec $filemanager

#Window resizing
mode "resize" {
        bindsym j resize shrink width 2 px or 2 ppt
        bindsym k resize grow height 2 px or 2 ppt
        bindsym l resize shrink height 2 px or 2 ppt
        bindsym ccaron resize grow width 2 px or 2 ppt

        bindsym Left resize shrink width 2 px or 2 ppt
        bindsym Down resize grow height 2 px or 2 ppt
        bindsym Up resize shrink height 2 px or 2 ppt
        bindsym Right resize grow width 2 px or 2 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}
bindsym $mod+r mode "resize"

# Bindings for every ROFI thing that I use
bindsym $mod+b exec nbrowser
bindsym $mod+d exec rofi -show drun

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# Manualy split window [Vertical or Horizontal]
bindsym $mod+h split h
bindsym $mod+v split v

# Define what Actions will user pick ????
mode "Actions: Loc[K] | [L]ogout | [R]eboot | [H]ibernate | [S]hutdown"
{
	bindsym K exec i3lock -i ~/Pictures/WallPP/Colorschemes/gruvbox/fedora_center.png -t, mode "default"
	bindsym L exec i3-msg exit, mode "default"
	bindsym R exec systemctl reboot, mode "default"
	bindsym H exec systemctl suspend, mode "default"
	bindsym S exec systemctl poweroff, mode "default"
	bindsym Escape mode "default"
 bindsym Return mode "default"
}
bindsym $mod+shift+a mode "Actions: Loc[K] | [L]ogout | [R]eboot | [H]ibernate | [S]hutdown"

# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# Sreen brightness controls
bindsym XF86MonBrightnessUp exec light -A 5 # Increase screen brightness by 5
bindsym XF86MonBrightnessDown exec light -U 5 # Decrease screen brightness by 5

# Media player controls
bindsym XF86AudioPlay exec playerctl play
bindsym XF86AudioStop exec playerctl pause
bindsym XF86AudioNext exec playerctl next
bindsym XF86AudioPrev exec playerctl previous

# Take a screenshot and saves it [or choose part of the screen]
bindsym --release $mod+x exec --no-startup-id import ~/Pictures/Screenshots/screen-tmp.png
bindsym Print exec scrot ~/Pictures/Screenshots/Screenshot.png && notify-send "Screenshot Took!" "Saved in ~/Pictures folder."
