# Set gaps for i3-gaps
gaps inner 10
gaps outer 15
smart_gaps on


# Window's Title bar
new_window 1pixel
hide_edge_borders smart
default_floating_border none
default_floating_border normal 0
for_window [class=".*"] border pixel 2


# i3run Scratchpads
for_window [class="Pavucontrol|KeePassXC"] border pixel 6, floating enable, resize set 1250 850, move position center
for_window [title="FakeAssTaskManager|RangerFileManager"] border pixel 6, floating enable, resize set 1250 850, move position center

bindsym $mod+Shift+ctrl+k exec i3run --class KeePassXC -s keepassxc
bindsym $mod+Shift+ctrl+p exec i3run --class Pavucontrol -s pavucontrol
bindsym $mod+Shift+ctrl+c exec i3run --title KDEConnect -s kdeconnect-app
bindsym $mod+Shift+ctrl+r exec i3run --title RangerFileManager -s -- kitty --title RangerFileManager -e ranger
bindsym $mod+Shift+ctrl+h exec i3run --title FakeAssTaskManager -s -- kitty --title FakeAssTaskManager -e htop
