#!/usr/bin/bash

hc () { herbstclient "$@" ;}
hc_s () { herbstclient set "$@" ;}
hc_r () { herbstclient rule "$@" ;}
hc_a () { herbstclient attr "$@" ;}
hc_k () { herbstclient keybind "$@" ;}

hc emit_hook reload
hc_s swap_monitors_to_get_tag 1
hc_s default_frame_layout horizontal
hc_s focus_crosses_monitor_boundaries 1

# THEME #
#-------#
source $HOME/.config/herbstluftwm/confs.d/theme

# RULES #
#-------#
source $HOME/.config/herbstluftwm/confs.d/winRules

# KEYBINDINGS #
#-------------#
source $HOME/.config/herbstluftwm/confs.d/keybindings

# MONITOR RECOGNITION #
#---------------------#
bash -c $HOME/.config/herbstluftwm/scripts/monitor_init.sh &

# AUTOSTART #
#-----------#
xfdesktop &
clipmenud &
numlockx on &
xfce4-panel &
#killall -q xfce4-panel | wait; bash -c ~/.config/herbstluftwm/scripts/polybar.sh &
