#!/usr/bin/bash

hc () { herbstclient "$@" ;}
hc_r () { herbstclient rule "$@" ;}
hc_s () { herbstclient set "$@" ;}
hc_a () { herbstclient attr "$@" ;}
hc_k () { herbstclient keybind "$@" ;}

hc emit_hook reload
hc_s swap_monitors_to_get_tag 1
hc_s default_frame_layout horizontal
hc_s focus_crosses_monitor_boundaries 1

# THEME #
#-------#
source $HOME/.config/herbstluftwm/confs.d/theme

# RULES #
#-------#
source $HOME/.config/herbstluftwm/confs.d/winRules

# KEYBINDINGS #
#-------------#
source $HOME/.config/herbstluftwm/confs.d/keybindings

# MONITOR RECOGNITION #
#---------------------#
bash -c $HOME/.config/herbstluftwm/scripts/monitor_init.sh &

# AUTOSTART #
#-----------#
xkbset q &
nm-applet &
#xfdesktop &
clipmenud &
xset b off &
numlockx on &
xfce4-panel &
unclutter -idle 20 &
killall -q xfce4-notifyd &
killall -q dunst | wait; dunst -config ~/.config/dunst/dunstrc &
killall -q picom | wait; picom --config ~/.config/picom/picom.conf &
i3-battery-popup -n -v 100 -L 20 -l 10 -s ~/.config/i3/audio/warning.wav &
xinput set-prop "MSFT0001:00 04F3:31BE Touchpad" "libinput Tapping Enabled" 1 & 
#killall -q xfce4-panel | wait; bash -c ~/.config/herbstluftwm/scripts/polybar.sh &
